screen: Fix screen index method
Before this, screen[1] caused a panic:

  thread 'Lua thread' panicked at 'index out of bounds: the len is 1 but
  the index is 1', src/liballoc/vec.rs:1552:10

Signed-off-by: Uli Schlachter <psychon@znc.in>